# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard_Window(object):
    def setupUi(self, Dashboard_Window):
        Dashboard_Window.setObjectName("Dashboard_Window")
        Dashboard_Window.resize(915, 688)
        Dashboard_Window.setMaximumSize(QtCore.QSize(1280, 895))
        Dashboard_Window.setStyleSheet("QMainWindow {\n"
"    background-color: #1C1C1C;\n"
"    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(Dashboard_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setMinimumSize(QtCore.QSize(0, 0))
        self.sidebar.setStyleSheet("*{\n"
"    margin: 0;\n"
"}\n"
"\n"
"#sidebar {\n"
"    background-color: #2B2B2B;\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"#logo {\n"
"\n"
"}\n"
"\n"
"#logo_text {\n"
"    color: #D0F565;\n"
"    \n"
"}\n"
"\n"
"#dashboard_logo {\n"
"    margin-top: 20px;\n"
"    margin-left: 15px;\n"
"}\n"
"\n"
"#dashboard_text {\n"
"    margin-top: 20px;\n"
"    margin-left: 8px;\n"
"}\n"
"\n"
"#reports_logo {\n"
"    margin-top: 20px;\n"
"    margin-left: 16px;\n"
"}\n"
"\n"
"#reports_text {\n"
"    margin-top: 20px;\n"
"    margin-left: 8px;\n"
"}\n"
"\n"
"#manage_logo {\n"
"    margin-top: 20px;\n"
"    margin-left: 12px;\n"
"}\n"
"\n"
"#manage_text {\n"
"    margin-top: 20px;\n"
"    margin-left: 8px;\n"
"}\n"
"\n"
"#generate_logo {\n"
"    margin-top: 20px;\n"
"    margin-left: 12px;\n"
"}\n"
"\n"
"#generate_text {\n"
"    margin-top: 20px;\n"
"    margin-left: 8px;\n"
"}\n"
"\n"
"#profile_logo {\n"
"    margin-top: 20px;\n"
"    margin-left: 12px;\n"
"}\n"
"\n"
"#profile_text {\n"
"    margin-top: 20px;\n"
"    margin-left: 9px;\n"
"}\n"
"\n"
"#logout_button {\n"
"    height: 33px;\n"
"    background-color: #CAFF33;\n"
"    color: #1C1C1C;\n"
"    margin: 0px 11px 30px 11px;\n"
"    border-radius: 11px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 20, 3, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(50, 50))
        self.logo.setMaximumSize(QtCore.QSize(30, 50))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/pics/—Pngtree—lightning-icon-electric-logo_8832878.ico"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.logo_text = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.logo_text.setFont(font)
        self.logo_text.setObjectName("logo_text")
        self.horizontalLayout.addWidget(self.logo_text)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dashboard_logo = QtWidgets.QLabel(self.sidebar)
        self.dashboard_logo.setMaximumSize(QtCore.QSize(40, 50))
        self.dashboard_logo.setText("")
        self.dashboard_logo.setPixmap(QtGui.QPixmap(":/icons/ui icons/Vector123.svg"))
        self.dashboard_logo.setObjectName("dashboard_logo")
        self.horizontalLayout_2.addWidget(self.dashboard_logo)
        self.dashboard_text = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_text.setFont(font)
        self.dashboard_text.setObjectName("dashboard_text")
        self.horizontalLayout_2.addWidget(self.dashboard_text)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reports_logo = QtWidgets.QLabel(self.sidebar)
        self.reports_logo.setMaximumSize(QtCore.QSize(40, 50))
        self.reports_logo.setText("")
        self.reports_logo.setPixmap(QtGui.QPixmap(":/icons/ui icons/Vector.svg"))
        self.reports_logo.setObjectName("reports_logo")
        self.horizontalLayout_3.addWidget(self.reports_logo)
        self.reports_text = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.reports_text.setFont(font)
        self.reports_text.setObjectName("reports_text")
        self.horizontalLayout_3.addWidget(self.reports_text)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.manage_logo = QtWidgets.QLabel(self.sidebar)
        self.manage_logo.setMaximumSize(QtCore.QSize(40, 50))
        self.manage_logo.setText("")
        self.manage_logo.setPixmap(QtGui.QPixmap(":/icons/ui icons/Icon.svg"))
        self.manage_logo.setObjectName("manage_logo")
        self.horizontalLayout_4.addWidget(self.manage_logo)
        self.manage_text = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.manage_text.setFont(font)
        self.manage_text.setObjectName("manage_text")
        self.horizontalLayout_4.addWidget(self.manage_text)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.generate_logo = QtWidgets.QLabel(self.sidebar)
        self.generate_logo.setMaximumSize(QtCore.QSize(40, 50))
        self.generate_logo.setText("")
        self.generate_logo.setPixmap(QtGui.QPixmap(":/icons/ui icons/basil_invoice-solid.svg"))
        self.generate_logo.setObjectName("generate_logo")
        self.horizontalLayout_5.addWidget(self.generate_logo)
        self.generate_text = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.generate_text.setFont(font)
        self.generate_text.setObjectName("generate_text")
        self.horizontalLayout_5.addWidget(self.generate_text)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.profile_logo = QtWidgets.QLabel(self.sidebar)
        self.profile_logo.setMaximumSize(QtCore.QSize(40, 50))
        self.profile_logo.setText("")
        self.profile_logo.setPixmap(QtGui.QPixmap(":/icons/ui icons/mdi_clipboard-user.svg"))
        self.profile_logo.setObjectName("profile_logo")
        self.horizontalLayout_6.addWidget(self.profile_logo)
        self.profile_text = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.profile_text.setFont(font)
        self.profile_text.setObjectName("profile_text")
        self.horizontalLayout_6.addWidget(self.profile_text)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.logout_button = QtWidgets.QPushButton(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_button.setObjectName("logout_button")
        self.verticalLayout.addWidget(self.logout_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_7.addWidget(self.sidebar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.page_1.setFont(font)
        self.page_1.setStyleSheet("QLabel {\n"
"    color: #D0F565;\n"
"}\n"
"\n"
"#pages_text {\n"
"    margin-left: 20px;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"#mainDashboard_text {\n"
"    margin-left: 18px;\n"
"}")
        self.page_1.setObjectName("page_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pages_text = QtWidgets.QLabel(self.page_1)
        self.pages_text.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(9)
        self.pages_text.setFont(font)
        self.pages_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pages_text.setObjectName("pages_text")
        self.verticalLayout_3.addWidget(self.pages_text)
        self.mainDashboard_text = QtWidgets.QLabel(self.page_1)
        self.mainDashboard_text.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mainDashboard_text.setFont(font)
        self.mainDashboard_text.setObjectName("mainDashboard_text")
        self.verticalLayout_3.addWidget(self.mainDashboard_text)
        self.frame = QtWidgets.QFrame(self.page_1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        Dashboard_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dashboard_Window)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dashboard_Window)

    def retranslateUi(self, Dashboard_Window):
        _translate = QtCore.QCoreApplication.translate
        Dashboard_Window.setWindowTitle(_translate("Dashboard_Window", "MainWindow"))
        self.logo_text.setText(_translate("Dashboard_Window", "USTEPALCO"))
        self.dashboard_text.setText(_translate("Dashboard_Window", "Dashboard"))
        self.reports_text.setText(_translate("Dashboard_Window", "Reports"))
        self.manage_text.setText(_translate("Dashboard_Window", "Manage Users"))
        self.generate_text.setText(_translate("Dashboard_Window", "Generate Bill"))
        self.profile_text.setText(_translate("Dashboard_Window", "Profile"))
        self.logout_button.setText(_translate("Dashboard_Window", "Logout"))
        self.pages_text.setText(_translate("Dashboard_Window", "Pages / Dashboard"))
        self.mainDashboard_text.setText(_translate("Dashboard_Window", "Main Dashboard"))
        self.label_3.setText(_translate("Dashboard_Window", "Merry Christmas!!!"))
import resource_rc
