# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 704)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 895))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/resources/stylized_00000.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #1C1C1C;\n"
"    \n"
"}\n"
"\n"
"#frame {\n"
"    width: 300px;\n"
"    background-color: #CAFF33;\n"
"    border-bottom-left-radius: 35px;\n"
"}\n"
"\n"
"#frame_2 {\n"
"    margin-left: 100px;\n"
"    margin-bottom: 50px;\n"
"    min-width: 500px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(16)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    margin: 5px 15px 5px 8px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    height: 42px;\n"
"    margin: 5px 70px 5px 8px;\n"
"    padding-left: 15px;\n"
"    border: 1px solid rgba(250, 250, 250, 0.5);\n"
"    border-radius: 15px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    max-width: 600px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgba(250, 250, 250, 1);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgba(250, 250, 250, 1);\n"
"}\n"
"\n"
"QPushButton {\n"
"    margin: 5px 310px 5px 8px;\n"
"    background-color: #CAFF33;\n"
"    border: 0px solid white;\n"
"    border-radius: 15px;\n"
"    height: 45px;\n"
"    max-width: 300px;\n"
"}\n"
"\n"
"#button_login:hover {\n"
"    background-color: #2A2A2A;\n"
"    color: #CAFF33;\n"
"}\n"
"\n"
"#line {\n"
"    margin: 8px 110px 5px 11px;\n"
"    max-width: 400px;\n"
"    \n"
"}\n"
"\n"
"#label_login_page {\n"
"    color: #D0F565;\n"
"    margin: 50px 0px 3px 0px;\n"
"}\n"
"\n"
"#label_welcome {\n"
"    margin: 2px 15px 0px 8px;\n"
"}\n"
"\n"
"#label_email {\n"
"    margin: 25px 15px 5px 8px;\n"
"}\n"
"\n"
"#label_email::first-letter {\n"
"    color: red;\n"
"}\n"
"\n"
"#forget_button {\n"
"    color: #CAFF33;\n"
"    margin-right: 10px;\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"}\n"
"\n"
"#forget_button:hover {\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 104, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login_page = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_login_page.setFont(font)
        self.label_login_page.setObjectName("label_login_page")
        self.verticalLayout.addWidget(self.label_login_page)
        self.label_welcome = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(10)
        self.label_welcome.setFont(font)
        self.label_welcome.setObjectName("label_welcome")
        self.verticalLayout.addWidget(self.label_welcome)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_email = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans Medium")
        font.setPointSize(10)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.edit_email = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(10)
        self.edit_email.setFont(font)
        self.edit_email.setObjectName("edit_email")
        self.verticalLayout.addWidget(self.edit_email)
        self.label_password = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans Medium")
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.edit_password = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(10)
        self.edit_password.setFont(font)
        self.edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_password.setObjectName("edit_password")
        self.verticalLayout.addWidget(self.edit_password)
        self.forget_button = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans Medium")
        font.setPointSize(10)
        self.forget_button.setFont(font)
        self.forget_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forget_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.forget_button.setObjectName("forget_button")
        self.verticalLayout.addWidget(self.forget_button)
        self.button_login = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_login.setFont(font)
        self.button_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_login.setObjectName("button_login")
        self.verticalLayout.addWidget(self.button_login)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 104, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame.setStyleSheet("* {\n"
"    margin: 0px;\n"
"}\n"
"\n"
"#label_logo_text {\n"
"    color: #3E3939;\n"
"    margin: 0px 5px 200px 5px;\n"
"\n"
"}\n"
"\n"
"#label_logo {\n"
"    margin: 150px 5px 0px 5px;    \n"
"    height: 10px;\n"
"    position: absolute;\n"
"    top: 2px;\n"
"    left:  2px;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_logo = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setMinimumSize(QtCore.QSize(50, 0))
        self.label_logo.setText("")
        self.label_logo.setTextFormat(QtCore.Qt.PlainText)
        self.label_logo.setPixmap(QtGui.QPixmap(":/logo/resources/inverted (black bg, resized).png"))
        self.label_logo.setScaledContents(False)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setWordWrap(False)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout_2.addWidget(self.label_logo)
        self.label_logo_text = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo_text.sizePolicy().hasHeightForWidth())
        self.label_logo_text.setSizePolicy(sizePolicy)
        self.label_logo_text.setMinimumSize(QtCore.QSize(50, 0))
        self.label_logo_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_logo_text.setFont(font)
        self.label_logo_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo_text.setObjectName("label_logo_text")
        self.verticalLayout_2.addWidget(self.label_logo_text)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_login_page.setText(_translate("MainWindow", "Login Page"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome to USTEPALCO! Enter your email and password!"))
        self.label_email.setText(_translate("MainWindow", "Email*"))
        self.edit_email.setPlaceholderText(_translate("MainWindow", "example@gmail.com"))
        self.label_password.setText(_translate("MainWindow", "Password*"))
        self.edit_password.setPlaceholderText(_translate("MainWindow", "Min. of 8 characters"))
        self.forget_button.setText(_translate("MainWindow", "Forget Password?"))
        self.button_login.setText(_translate("MainWindow", "Login"))
        self.label_logo_text.setText(_translate("MainWindow", "USTEPALCO"))
import resource_rc
